[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
commands = ["python3", "gcc"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.start]
cmd = "gunicorn -w 4 -b 0.0.0.0:${PORT:-5000} app:app"
